name: Alexander.id
favicon: null
layout_spectrum: 0
typography_spectrum: 0.52835
title: Random Musings of a Digital Enthusiast
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#99c9dd'
    - '#00acee'
    - '#ffffff'
    - '#101010'
    - '#4e6670'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
