name: Alexander.id
favicon: null
layout_spectrum: 0.99477
typography_spectrum: 0.52835
title: Random Musings of a Digital Enthusiast
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f1f2f4'
    - '#d0beb4'
    - '#000000'
    - '#a4744e'
    - '#6a8dad'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 1
  rhythmicContrast: 1
purpose: []
